### PR TITLE
Create AppImage of the master branch

### PR DESCRIPTION
**Pull request by probonopd**
Releases could be uploaded to GitHub Releases

### CODE REVIEW

**Comment by probonopd** [comment]
You might want to change it slightly so that upon releases, the AppImage gets deployed to GitHub Releases automatically. 

https://docs.travis-ci.com/user/deployment/releases/

**Comment by dannagle** [comment]
I'm new to Travis CI. I'm not so much concerned about deployment right now. If it helps Linux users, even better. My main goal was getting automated testing. 

How do I resolve the README passing image pointing to different branches? I want to merge.

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional(!) desktop integration with `appimaged`
- Binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can GPG2-sign your AppImages (inside the file)

When you want to merge into master, then use the version of the Travis CI README.md badge that is currently in master.

**Comment by dannagle** [comment]
AppImage looks pretty cool. Packaging in to a single universal binary that runs on most Linux distros would be nice. I'll look in to this more when I have time. Thanks helping me with the Travis script to get it started.

**Comment by probonopd** [comment]
On each build, you'll see a download link towards the end of the Travis CI build log for the AppImage. Just download, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run.

**Pull request merged**
